services:
  agenda_viagens:
    image: postgres:16
    container_name: agenda-viagens-db
    environment:
      POSTGRES_DB: agenda_viagens
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: agenda-viagens-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - agenda_viagens