spring.application.name=agenda-viagens

# BANCO DE DADOS
spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_viagens
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha